# Generated by Django 5.1.15 on 2026-04-25 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='dm_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_message_at',),
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio')], default='text', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='dm_attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_sent', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='direct_messages.conversation')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='direct_mess_convers_7a6780_idx')],
            },
        ),
    ]
